apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-3
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: mynode
            operator: In
            values:
            - worker-2
  containers:
  - name: nginx
    image: nginx