apiVersion: v1
kind: Pod
metadata:
  name: with-node-affinity-2
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: mynode
            operator: In
            values:
            - worker-2
  containers:
  - name: nginx
    image: nginx